apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devopshere.fullname" . }}-config
  labels:
    {{- include "devopshere.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
