apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devopshere.fullname" . }}
  labels:
    {{- include "devopshere.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devopshere.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devopshere.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podLabels }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "devopshere.fullname" .) }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "devopshere.fullname" . }}-config
          env:
            - name: APP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runtimeSecretName }}
                  key: APP_DATABASE_URL
            - name: APP_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runtimeSecretName }}
                  key: APP_REDIS_URL
          startupProbe:
            httpGet: {path: /health/live, port: http}
            periodSeconds: 5
            failureThreshold: 24
          livenessProbe:
            httpGet: {path: /health/live, port: http}
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet: {path: /health/ready, port: http}
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}nodeSelector: {{ toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.affinity }}affinity: {{ toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.tolerations }}tolerations: {{ toYaml . | nindent 8 }}{{- end }}
